// Type definitions for plugins.js
// Project: [LIBRARY_URL_HERE] 
// Definitions by: [YOUR_NAME_HERE] <[YOUR_URL_HERE]> 
// Definitions: https://github.com/borisyankov/DefinitelyTyped
/// <reference path="\TkoolTsdrpgmakermv.d.ts" />
declare namespace $plugins.0{
	// $plugins.0
	
	/**
	 * 
	 */
	interface 0 {
				
		/**
		 * 
		 */
		name : string;
				
		/**
		 * 
		 */
		status : boolean;
				
		/**
		 * 
		 */
		description : string;
		
		/**
		 * 
		 */
		parameters : {
						
			/**
			 * 
			 */
			cacheLimit : string;
						
			/**
			 * 
			 */
			screenWidth : string;
						
			/**
			 * 
			 */
			screenHeight : string;
						
			/**
			 * 
			 */
			changeWindowWidthTo : string;
						
			/**
			 * 
			 */
			changeWindowHeightTo : string;
						
			/**
			 * 
			 */
			renderingMode : string;
						
			/**
			 * 
			 */
			alwaysDash : string;
		}
	}
}
declare namespace $plugins.1{
	// $plugins.1
	
	/**
	 * 
	 */
	interface 1 {
				
		/**
		 * 
		 */
		name : string;
				
		/**
		 * 
		 */
		status : boolean;
				
		/**
		 * 
		 */
		description : string;
		
		/**
		 * 
		 */
		parameters : {
						
			/**
			 * 
			 */
			Show Made With MV : string;
						
			/**
			 * 
			 */
			Made with MV Image : string;
						
			/**
			 * 
			 */
			Show Custom Splash : string;
						
			/**
			 * 
			 */
			Custom Image : string;
						
			/**
			 * 
			 */
			Fade Out Time : string;
						
			/**
			 * 
			 */
			Fade In Time : string;
						
			/**
			 * 
			 */
			Wait Time : string;
		}
	}
}
declare namespace $plugins.2{
	// $plugins.2
	
	/**
	 * 
	 */
	interface 2 {
				
		/**
		 * 
		 */
		name : string;
				
		/**
		 * 
		 */
		status : boolean;
	}
}
declare namespace $plugins.3{
	// $plugins.3
	
	/**
	 * 
	 */
	interface 3 {
				
		/**
		 * 
		 */
		name : string;
				
		/**
		 * 
		 */
		status : boolean;
	}
}
declare namespace $plugins.4{
	// $plugins.4
	
	/**
	 * 
	 */
	interface 4 {
				
		/**
		 * 
		 */
		name : string;
				
		/**
		 * 
		 */
		status : boolean;
				
		/**
		 * 
		 */
		description : string;
		
		/**
		 * 
		 */
		parameters : {
						
			/**
			 * 
			 */
			開始時に起動 : string;
						
			/**
			 * 
			 */
			デベロッパツール表示位置 : string;
						
			/**
			 * 
			 */
			最小化切替キー : string;
						
			/**
			 * 
			 */
			リロードキー : string;
						
			/**
			 * 
			 */
			最前面に表示キー : string;
						
			/**
			 * 
			 */
			高速化切替キー : string;
						
			/**
			 * 
			 */
			強制戦闘勝利キー : string;
						
			/**
			 * 
			 */
			スクリプト実行キー : string;
						
			/**
			 * 
			 */
			フリーズキー : string;
						
			/**
			 * 
			 */
			FPS表示 : string;
						
			/**
			 * 
			 */
			タイトルカット : string;
						
			/**
			 * 
			 */
			高速開始 : string;
						
			/**
			 * 
			 */
			高速スピード : string;
						
			/**
			 * 
			 */
			モバイル偽装 : string;
						
			/**
			 * 
			 */
			メニューバー表示 : string;
						
			/**
			 * 
			 */
			クリックメニュー : string;
						
			/**
			 * 
			 */
			JSON形式セーブ : string;
						
			/**
			 * 
			 */
			起動時情報出力 : string;
						
			/**
			 * 
			 */
			最前面で起動 : string;
						
			/**
			 * 
			 */
			リロード機能を使う : string;
		}
	}
}

/**
 * Generated by RPG Maker.
 * Do not edit this file directly.
 */
export declare var $plugins : Array</* $plugins.0,$plugins.1,$plugins.2,$plugins.3,$plugins.4 */ any>;
