// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"mscorlib","status":true,"description":null,"parameters":null},
{"name":"TkoolOfJavascriptTheCross","status":true,"description":null,"parameters":null},
{"name":"DevToolsManage","status":true,"description":"総合開発支援プラグイン","parameters":{"開始時に起動":"ON","デベロッパツール表示位置":"","最小化切替キー":"F8","リロードキー":"F12","最前面に表示キー":"F11","高速化切替キー":"","強制戦闘勝利キー":"","スクリプト実行キー":"","フリーズキー":"F10","FPS表示":"FPS","タイトルカット":"false","高速開始":"false","高速スピード":"2","モバイル偽装":"false","メニューバー表示":"true","クリックメニュー":"1","JSON形式セーブ":"false","起動時情報出力":"true","最前面で起動":"false","リロード機能を使う":"true"}}
];
